language: node_js
node_js:
- 12
jobs:
  include:
  - stage: test
    name: Unit Tests
    script: "npm ci && npm test"

stages:
- name: test
  if: type = pull_request

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: discord-mod
  run: 
    - heroku dh:compose down
    - heroku dh:compose up --build -d
